SSD_Driver/SSD_Driver.vcxproj, SSD_Driver/main.cpp, SSD_Driver/ssd.cpp, SSD_Driver/ssd.h
=> [feat] Start SSD Program with main func

SSD_TestShell/shell_command.h
[feat] shell command interface init upload
: void set(string): 초기 command 생성 시 command 설정을 위한 method 
: bool run(): command 동작을 위한 method, 동작 성공 시 true, 실패 시 false 반환
=> [feat] shell command interface init upload

SSD_TestShell/SSD_TestShell.vcxproj, SSD_TestShell/SSD_TestShell.vcxproj.filters, SSD_TestShell/command_processer.cpp, SSD_TestShell/command_processer.h, SSD_TestShell/exit_command.cpp, SSD_TestShell/exit_command.h, SSD_TestShell/full_read_command.cpp, SSD_TestShell/full_read_command.h, SSD_TestShell/full_write_command.cpp, SSD_TestShell/full_write_command.h, SSD_TestShell/help_command.cpp, SSD_TestShell/help_command.h, SSD_TestShell/read_command.cpp, SSD_TestShell/read_command.h, SSD_TestShell/write_command.cpp, SSD_TestShell/write_command.h
read, write, exit, help, fullwrite, fullread에 대한 interface 추가하였습니다.
=> [feature] add skeleton code for commands

SSD_TestShell/ssd_mock.h
[feat] SSD Mock init upload
- SSD의 R, W에 대한 Mock 입니다.
- ./ssd.exe에 대한 System Call은 별도 처리 필요합니다.
=> [feat] SSD Mock init upload

SSD_Driver/ssd.h
ssd read/write 동작 수행할 memory address에 mapping 되는 멤버 변수 추가
=> [feat] add member varialbe for ssd memory

SSD_TestShell/SSD_TestShell.vcxproj, SSD_TestShell/test/mock_command_processer.h
=> [test] add test folder

SSD_Driver/SSD_Driver.vcxproj, SSD_Driver/main.cpp, SSD_Driver/ssd.cpp, SSD_Driver/ssd.h, SSD_Driver/write_test.cpp
ssd write function
UT for write and write exception
=> [Feat] Introduce ssd write function

SSD_TestShell/SSD_TestShell.vcxproj, SSD_TestShell/parser.cpp, SSD_TestShell/parser.h
read / write parser의 공통 기능들을 method로 분리했습니다.
- 입력된 command의 token 개수를 확인하는 method
- 입력된 address 또는 value의 validation method
=> [refactor] extract common logic in parser.cpp into helper function

SSD_TestShell/command_mock.h, SSD_TestShell/test_script.cpp, SSD_TestShell/test_script_test.cpp
[feature] test script init upload
- test script를 TDD 원칙에 따라 간단한 UT 구성 후 통과하는 코드로만 추가해두었습니다.
- Command Mock을 구성하여 실제 set, run command 동작 없이 동작 횟수로만 UT에서 확인합니다.
=> [feature] test script init upload

SSD_Driver/main.cpp
16 진수 input에 대한 처리하는 부분 추가했습니다.
=> [Feat] Consider hex input

SSD_TestShell/erase_and_write_aging_command.cpp, SSD_TestShell/erase_and_write_aging_command.h, SSD_TestShell/ssd_handler.h, SSD_TestShell/test_script_command_test.cpp
[feature] add test script: 4_EraseAndWriteAging command
-  4_EraseAndWriteAging command 추가 하였습니다.
-  테스트를 위해 sdd_handler.h에 erase, flush interface와 mock 수정하였습니다.
=> [feature] add test script: 4_EraseAndWriteAging command

SSD_TestShell/SSD_TestShell.vcxproj, SSD_TestShell/parser/validator.h, SSD_TestShell/parser/validator_factory.h, SSD_TestShell/test/parser_test.cpp
- Add unit tests for script command
- Enable parser to handle scripts command
Also I refactored validator to remove some magic strings (commands)
=> [feat] Enable parser to handle scripts

SSD_TestShell/main.cpp, SSD_TestShell/ssd_client_app.cpp, SSD_TestShell/ssd_client_app.h, SSD_TestShell/ssd_client_app_test.cpp
SsdClientApp과 SsdClientAppTest 및 main 함수 수정건입니다.
Testcase추가했고 요구사항대로 error 및 result가 출력하게 했습니다.
=> [Fix] Fix ClientApp & ClientAppTest

SSD_Driver/bufferManager.cpp, SSD_Driver/bufferManger_test.cpp
Command Buffer 기능 추가하였습니다. 
아직 flush는 구현 안되었습니다.
=> [feature] Implement Buffer System without flush

SSD_TestShell/help_command.cpp
help에 만든 사람 추가하였습니다.
신규 command도 추가하였습니다.
=> [feature] add name

SSD_TestShell/SSD_TestShell.vcxproj, SSD_TestShell/main.cpp, SSD_TestShell/runner.cpp, SSD_TestShell/runner.h, SSD_TestShell/shell_script.txt, SSD_TestShell/test/runner_test.cpp
Runner 추가했습니다.
동작확인 완료되었고, SSD_Driver.exe를 실행시키기 위해 SSD_TestShell.exe와  shell_script.txr가 있는 SSD_TestShell\x64\Release 폴더에 SSD_Driver.exe를 직접 넣어주셔야 합니다.
=> [Feature] Add Runner

SSD_TestShell/runner.cpp, SSD_TestShell/runner.h, SSD_TestShell/test/runner_test.cpp
Runner 리팩토링 건입니다.
Runner Test는 오래걸려 주석처리 했습니다.
Mock으로 테스트 변경 예정입니다.
=> [refactoring] Runner Refactoring

SSD_Driver/SSD_Driver.vcxproj, SSD_Driver/buffer_manager.cpp, SSD_Driver/buffer_manager.h, SSD_Driver/buffer_manager_test.cpp, SSD_Driver/command_strategy.cpp, SSD_Driver/command_strategy.h, SSD_Driver/main.cpp
addCommand 할때 복잡성을 줄이기 위해 W/E 로직을 대상으로 패턴을 구현하였습니다.
=> [refactoring] Add Strategy Pattern

SSD_Driver/SSD_Driver.vcxproj, SSD_Driver/buffer_manager.cpp, SSD_Driver/buffer_manager_test.cpp
addCommand가 될때마다 buffer 파일을 새로 만드는 구조에서
-> renaming 만 하는 방식으로 변경했습니다.
=> [feature] Modify updateBufferFile

SSD_TestShell/erase_and_write_aging_command.cpp, SSD_TestShell/full_write_and_read_compare_command.cpp, SSD_TestShell/partial_lba_write_command.cpp, SSD_TestShell/utils.h, SSD_TestShell/write_read_aging_command.cpp
[refactoring] test script add PASS/FAIL LOG
- 4개의 test script command의 PASS/FAIL 위치에 LOG를 추가하여 logging이 되도록 변경하였습니다.
=> [refactoring] test script add PASS/FAIL LOG

SSD_TestShell/command.h, SSD_TestShell/erase_command.cpp, SSD_TestShell/erase_range_command.cpp, SSD_TestShell/exit_command.cpp, SSD_TestShell/flush_command.cpp, SSD_TestShell/full_read_command.cpp, SSD_TestShell/full_write_command.cpp, SSD_TestShell/help_command.cpp, SSD_TestShell/logger/logger.h, SSD_TestShell/read_command.cpp, SSD_TestShell/write_command.cpp
command (read,write, flush 등)에 log 추가.
logger.h에 program once 추가.
=> [feature] add log in command

SSD_Driver/SSD_Driver.vcxproj, SSD_Driver/buffer_manager.cpp, SSD_Driver/buffer_manager.h, SSD_Driver/buffer_manager_test.cpp
=> [refactoring] buffer manager refactoring
